reqs:
  nvim:
    apt:
      - python3
      - python3-pip
      - python3-setuptools
    pip:
      - wheel
      - pynvim
install_steps:
  - rbenv-ctags:
      - install: |-
          mkdir -p ~/plugins
          git clone git://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
          rbenv ctags
